steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', 
  '--build-arg',
  'ARGOCD_VERSION=${_ARGOCD_VERSION}',
  '--build-arg',
  'VAULT_VERSION=${_VAULT_VERSION}',
  '--build-arg',
  'TERRAFORM_VERSION=${_TERRAFORM_VERSION}',
  '--build-arg',
  'SCW_VERSION=${_SCW_VERSION}',
  '--build-arg',
  'VAULT_CA=${_VAULT_CA}',
  '--build-arg',
  'GITLAB_SSH_KEY=${_GITLAB_SSH_KEY}',
  '-t', 'eu.gcr.io/${_PROJECT_ID}/tools:$_VERSION', 
  '.' ]

images:
   - 'eu.gcr.io/${_PROJECT_ID}/tools:$_VERSION'
